# Generated by Django 4.1 on 2022-10-30 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default=9271726354, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
