# Generated by Django 4.1 on 2022-10-30 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='Anshuman Gupta', max_length=100),
            preserve_default=False,
        ),
    ]
