# Generated by Django 4.1 on 2022-11-08 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Generic', max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('brand', models.CharField(max_length=100)),
                ('thumbnail', models.ImageField(null=True, upload_to='uploads/products/')),
                ('description', models.TextField()),
                ('category', models.ForeignKey(default='Generic', on_delete=django.db.models.deletion.SET_DEFAULT, to='store.category')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.seller')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=30)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.category')),
            ],
        ),
        migrations.AddConstraint(
            model_name='categoryfeature',
            constraint=models.UniqueConstraint(fields=('category', 'feature'), name='unique_category_feature_combination'),
        ),
    ]
